[book]
authors = ["patrick"]
language = "en"
multilingual = false
src = "src"
title = "Patrick's Web Archive"

[output.html]
theme = "src/theme"
default-theme = "light"
git-repository-url = "https://github.com/code-ink-space/webarchive"
git-repository-icon = "fa-github"